# Generated by Django 5.2.5 on 2025-08-24 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RFQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_email', models.EmailField(max_length=254)),
                ('product_name', models.CharField(max_length=200)),
                ('fabric', models.CharField(blank=True, max_length=200, null=True)),
                ('trim', models.CharField(blank=True, max_length=200, null=True)),
                ('accessories', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
