# Generated by Django 5.2.5 on 2025-08-24 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfq_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RFQCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('shopify_collection_id', models.CharField(max_length=50)),
            ],
        ),
    ]
