name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            set -e
            echo "⏳ Starting deployment..."

            cd /home/ubuntu/projectdir/rfq

            # Update code
            git reset --hard
            git pull origin main

            # Ensure venv dependencies exist
            sudo apt update
            sudo apt install -y python3-venv python3-pip

            # Create virtual environment if missing
            if [ ! -d "venv" ]; then
              python3 -m venv venv
            fi

            # Activate virtual environment
            source venv/bin/activate

            # Install dependencies
            pip install --upgrade pip
            pip install -r requirements.txt

            # Django tasks
            python manage.py migrate
            python manage.py collectstatic --noinput

            # Restart Gunicorn
            sudo systemctl restart gunicorn

            echo "✅ Deployment completed successfully!"
