name: Deploy Django to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        id: deploy
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            set -e  # Stop if any command fails
            echo "⏳ Starting deployment..."
            cd /home/ubuntu/projectdir/rfq
            git reset --hard
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            python manage.py migrate
            python manage.py collectstatic --noinput
            sudo systemctl restart gunicorn
            echo "✅ Deployment completed successfully!"

      - name: Deployment Result
        run: |
          if [ ${{ steps.deploy.outcome }} == 'success' ]; then
            echo "✅ Deployment succeeded!"
          else
            echo "❌ Deployment failed! Check workflow logs."
            exit 1
          fi
