name: Deploy Django to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            set -e
            echo "⏳ Starting deployment..."

            cd /home/ubuntu/projectdir/rfq

            # Pull latest code
            git reset --hard
            git pull origin main

            # Create virtual environment if missing
            if [ ! -d "venv" ]; then
              echo "🔹 Creating virtual environment..."
              python3 -m venv venv
            fi

            # Activate venv
            source venv/bin/activate

            # Upgrade pip and install requirements
            pip install --upgrade pip
            pip install -r requirements.txt
             pip install xhtml2pdf python-dotenv

            # Django settings: ensure STATIC_ROOT exists
            

            # Run migrations
            python manage.py migrate

            # Collect static files
            

            # Restart Gunicorn
            sudo systemctl restart gunicorn

            echo "✅ Deployment completed successfully!"
