name: Deploy Django to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          script: |
            set -e  # Stop on any error
            echo "⏳ Starting deployment..."

            cd /home/ubuntu/projectdir/rfq

            # Update code from GitHub
            git reset --hard
            git pull origin main

            # Ensure venv package is installed
            sudo apt update
            sudo apt install -y python3-venv python3-pip

            # Create virtual environment if missing
            if [ ! -d "venv" ]; then
              echo "🔹 Creating virtual environment..."
              python3 -m venv venv
            fi

            # Activate virtual environment
            source venv/bin/activate

            # Upgrade pip and install requirements
            pip install --upgrade pip
            pip install -r requirements.txt

            # Django migrations and static files
            python manage.py migrate
            python manage.py collectstatic --noinput

            # Restart Gunicorn
            sudo systemctl restart gunicorn

            echo "✅ Deployment completed successfully!"
