name: Deploy Django to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        id: deploy
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            set -e  # Stop script if any command fails
            cd /home/ubuntu/projectdir/rfq
            git reset --hard
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            python manage.py migrate
            python manage.py collectstatic --noinput
            sudo systemctl restart gunicorn

      - name: Deployment Success
        if: ${{ success() }}
        run: echo "✅ Deployment succeeded!"

      - name: Deployment Failed Notification
        if: ${{ failure() }}
        uses: actions/github-script@v7
        with:
          script: |
            github.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.runId,
              body: '❌ Deployment failed! Please check the workflow logs.'
            })
